name: CI on PR for app

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/app-ci.yaml'
      - 'src/**'
      - '!**/README.md'

jobs:
  test-app-demo:
    name: Test app-demo
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: './src/*.{ts,tsx,js,jsx}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          registry-url: https://npm.pkg.github.com
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install
      - run: yarn format
      - run: yarn lint
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CI changes